### ISSUE TITLE
PCCS docker container image build error

### ISSUE THREAD

**Issue by yangfh2004** [intel/confidential-computing.tee.dcap.pccs#23]
When using the dockerfile in `QuoteGeneration/pccs/container` to build an image for PCCS services, it will throw an error due to the missing SGX SDK dependency.

I reviewed the Makefile in the directory `/SGXDataCenterAttestationPrimitives/tools/PCKCertSelection/PCKCertSelectionLib`, and found that it needs to load the `QuoteGeneration/buildenv.mk`, which loads `/opt/intel/sgxsdk/buildenv.mk` as a part of SGX SDK. However, the SGX SDK is not installed in the base image `Ubuntu:22.04`. 

I think the builder phase installs SGX SDK should be done before building the dependent library.

**Comment by bgotowal** [comment]
This issue has been transferred from DCAP project, following PCCS detach to a dedicated GitHub project.

Original URL: https://github.com/intel/confidential-computing.tee.dcap/issues/355
