### ISSUE TITLE
Some problems about install DCAP as official website of intel

### ISSUE THREAD

**Issue by TY-cc** [intel/confidential-computing.tee.dcap.pccs#28]
[https://www.intel.cn/content/www/cn/zh/developer/articles/guide/intel-software-guard-extensions-data-center-attestation-primitives-quick-install-guide.html](url) is the method for PCCS' configuration.  
I edit the configuration file /opt/intel/sgx-pck-id-retrieval-tool/network_setting.conf as follow:
1、Change the PCCS_URL to match your caching service’s location(default).
2、Uncomment the user_token parameter, and set it to the user password you created when configuring the PCCS
3、Set the proxy_type to fit your environment (most likely this will be “direct”)
4、change USE_SECURE_CERT is set to “FALSE” 
Then the PCKIDRetrievalTool is succeed.

When I config the runtime configuration, i edit the configuration file /etc/aesmd.conf and restart AESM for the changes to take effect.
Then i edit the configuration file /etc/sgx_default_qcnl.conf as intel guidance:
1、Set the PCCS_URL parameter to the location of our PCCS server（it is default）
2、Set USE_SECURE_CERT to “FALSE”

[https://www.intel.cn/content/www/cn/zh/developer/articles/technical/quote-verification-attestation-with-intel-sgx-dcap.html](url) is the method for Sample' install.
It need install sgx-sdk, libsgx-dcap-ql-dev, libsgx-quote-ex-dev.
Report a error as blew when i run the "sudo ./app" after make the Sample/QuoteGeneration:

> sgx_qe_set_enclave_load_policy is valid in in-proc mode only and it is optional: the default enclave load policy is persistent:
> set the enclave load policy as persistent:succeed!
> Step1: Call sgx_qe_get_target_info:[get_platform_quote_cert_data ../qe_logic.cpp:378] Error returned from the p_sgx_get_quote_config API. 0xe019
> Error in sgx_qe_get_target_info. 0xe019

My /opt/intel/sgx-dcap-pccs/config/default.json is this and i don't modify it:

> {
> "HTTPS_PORT" : 8081,
> "hosts" : "0.0.0.0",
> "uri": "https://api.trustedservices.intel.com/sgx/certification/v3/",
> "ApiKey" : "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
> "proxy" : " ",
> "RefreshSchedule": "0 0 1 * * *",
> "UserTokenHash" : "34d4e4af145ccd2cfffc8d46ba76314d44b0eba921302246f0b8b4177749923afd648b68f5c08389a778511d270ccfaaefa4d03fb64c2a39aa4c3552ee60e0d7",
> "AdminTokenHash" : "34d4e4af145ccd2cfffc8d46ba76314d44b0eba921302246f0b8b4177749923afd648b68f5c08389a778511d270ccfaaefa4d03fb64c2a39aa4c3552ee60e0d7",
> "CachingFillMode" : "REQ",
> "LogLevel" : "info",
> "DB_CONFIG" : "sqlite",
> "sqlite" : {
> "database" : "database",
> "username" : "username",
> "password" : "password",
> "options" : {
> "host": "localhost",
> "dialect": "sqlite",
> "pool": {
> "max": 5,
> "min": 0,
> "acquire": 30000,
> "idle": 10000
> },
> "define": {
> "freezeTableName": true
> },
> "logging" : false,
> "storage": "pckcache.db"
> }
> },
> "mysql" : {
> "database" : "pckcache",
> "username" : "root",
> "password" : "mypass",
> "options" : {
> "host": "localhost",
> "dialect": "mysql",
> "pool": {
> "max": 5,
> "min": 0,
> "acquire": 30000,
> "idle": 10000
> },
> "define": {
> "freezeTableName": true
> },
> "logging" : false
> }
> }
> }

I don't know what should i do. Hope your reply

**Comment by bgotowal** [comment]
This issue has been transferred from DCAP project, following PCCS detach to a dedicated GitHub project.

Original URL: https://github.com/intel/confidential-computing.tee.dcap/issues/251
