### ISSUE TITLE
Install pccs problem

### ISSUE THREAD

**Issue by ltinerary** [intel/confidential-computing.tee.dcap.pccs#32]
I was download sgx-dcap-pccs follow this url [https://download.01.org/intel-sgx/sgx-dcap/1.10/linux/tools/SGXCertRetrievalTool/ubuntu18.04-server/debian_pkgs/web/sgx-dcap-pccs/sgx-dcap-pccs_1.10.100.4-bionic1_amd64.deb](https://download.01.org/intel-sgx/sgx-dcap/1.10/linux/tools/SGXCertRetrievalTool/ubuntu18.04-server/debian_pkgs/web/sgx-dcap-pccs/sgx-dcap-pccs_1.10.100.4-bionic1_amd64.deb)

(**First install**)So I install the .deb file use `sudo dpkg -i *.deb`,
and in my first install,
I set some wrong configurations(At that time,I didn't know we could change the configuration by changing default.json)
So I remove the `sgx-dcap-pccs` via `sudo dpkg -r sgx-dcap-pccs` and delete the whole folders(/opt/intel/sgx-dcap-pcss).

(**Second install**)Then,I reinstall the deb file and cames a error:
`can't  open /opt/intel/sgx-dcap-pccs/config/default.json.There is no file or directory`

I'm surprised why first was succesed and second was fialed?

Does anyone know how to solve this problem?

Thanks a lot!

**Comment by bgotowal** [comment]
This issue has been transferred from DCAP project, following PCCS detach to a dedicated GitHub project.

Original URL: https://github.com/intel/confidential-computing.tee.dcap/issues/172
